name: Master branch

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  code-scan:
    name: Code Scan
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
          cache: maven
      - name: Build with Maven and Coverage/Sonar
        run: mvn verify -P coverage,sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Codecov metrics
        uses: codecov/codecov-action@v2

  snapshots:
    name: Snaphots
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'carlosthe19916' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
          cache: maven
      - run: ls
      - run: cat settings.xml
      - name: OSSRH Snapshot
        run: mvn deploy -Possrh
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: GitHub Snapshot
        run: mvn deploy -Pgithub
        env:
          GITHUB_TOKEN: ${{ github.token }}
